version: '3.7'

services:
  db:
    env_file:
      - .env
    container_name: "platform_engineer_db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3337:3306"
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
  api:
    env_file:
      - .env
    container_name:  "platform_engineer_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    volumes:
      - .:/app/
    environment:
      DB_HOST: db

networks:
  default:
volumes:
  mysql_data: